# Docker compose to set up containers for all services you need:
# VPN
#   Sonarr, Radarr, Lidarr, Qbittorrent
# Non-VPN
#   Plex, get_iplayer
# Before running docker-compose, you should pre-create all of the following folders.
# Folders for Docker State:
#  /mnt/vol/dockerdata              - root where this docker-compose.yml should live
#  /mnt/vol/dockerdata/plex         - Plex config and DB
#  /mnt/vol/dockerdata/sonarr       - Sonarr config and DB
#  /mnt/vol/dockerdata/radarr       - Radarr config and DB
#  /mnt/vol/dockerdata/qbt          - QBitorrent config and DB
#  /mnt/vol/dockerdata/prowlarr     - Prowlarr config and DB
#  /mnt/vol/dockerdata/overseerr    - Overseerr config and DB
#  /mnt/vol/dockerdata/lib/modules  - Wireguard lib/modules
#  /mnt/vol/dockerdata/wireguard    - Wrieguard config
# 
# Folders for Media etc:
#  /mnt/vol/photo                   - Root storage for photo files
#  /mnt/vol/music                   - Root storage for music files
#  /mnt/vol/video                   - Root storage for video files
#  /mnt/vol/video/tv                - folder for Sonarr/Plex TV shows
#  /mnt/vol/video/movies            - folder for Radarr/Plex Movies
#  /mnt/vol/video/downloads         - QBT folder for TV downloads (that Sonarr will process)
#  /mnt/vol/video/downloadsMovies   - QBT folder for Movie downloads (that Radarr will process)
#
# Note that Sonarr and Radarr don't necessarily need the VPN if you're using Prowlarr for the indexers. 
# But Prowlarr should be behind the VPN to avoid ISPs that block indexers.

#
# Taken from: https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
# https://linuxiac.com/how-to-set-up-wireguard-vpn-with-docker/
#

# https://github.com/ivan-pinatti/docker-torrent-box-with-vpn

# https://github.com/RogueOneEcho/how-to-setup-deluge-with-protonvpn-portforward/tree/part-1 

---

services:
  ### ----------------- Plex ----------------- ###
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - /mnt/vol/dockerdata/plex:/config
      - /mnt/vol/video/tv:/tv
      - /mnt/vol/video/movies:/movies
    restart: unless-stopped
  ### ----------------- Sonarr --------------- ###
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/sonarr:/config
      - /mnt/vol/video/tv:/tv #optional
      - /mnt/vol/video/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.11
  ### ----------------- Radarr --------------- ###
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/radarr:/data
      - /mnt/vol/video/movies:/movies
      - /mnt/vol/video/downloadsMovies:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.12
  ### ----------------- Overseer ------------- ###
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.13
  ### ----------------- Prowlarr ------------ ###
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    # depends_on: 
    #   - wg-easy
    # network_mode: service:wg-easy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.14
  ### ----------------- Proton VPN ---------- ### 
  protonwire:
    container_name: protonwire
    image: ghcr.io/tprasadtp/protonwire:latest
    init: true
    restart: unless-stopped
    environment:
      PROTONVPN_SERVER: "149.40.58.146" 
      DEBUG: "0"
      # Set this to 0 to disable kill-switch
      KILL_SWITCH: "1"
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - /mnt/vol/dockerdata/protonwire:/etc/protonwire
    ports:
      # Qbit ports
      - 8080:8080
      - 16881:16881
      # Deluge Ports
      - 8112:8112
      - 17881:17881
      - 17881:17881/udp
      - 58846:58846 
    networks:
      container_net:
        ipv4_address: 172.28.1.20
  ### ----------------- QBitTorrent ---------- ### 
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbit
    network_mode: service:protonwire
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - TORRENTING_PORT=16881
    volumes:
      - /mnt/vol/dockerdata/qbt:/config
      - /mnt/vol/video/Downloads:/downloads # optional
  ### ----------------- Deluge ---------- ### 
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: service:protonwire
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DELUGE_LOGLEVEL=info
    volumes:
      - /mnt/vol/dockerdata/deluge:/config
      - /mnt/vol/video/Downloads:/downloads
    restart: unless-stopped

networks:
  container_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
          gateway: 172.28.1.1
