# Docker compose to set up containers for all services you need:
# VPN
#   Sonarr, Radarr, Lidarr, Qbittorrent
# Non-VPN
#   Plex, get_iplayer
# Before running docker-compose, you should pre-create all of the following folders.
# Folders for Docker State:
#  /mnt/vol/dockerdata              - root where this docker-compose.yml should live
#  /mnt/vol/dockerdata/plex         - Plex config and DB
#  /mnt/vol/dockerdata/sonarr       - Sonarr config and DB
#  /mnt/vol/dockerdata/radarr       - Radarr config and DB
#  /mnt/vol/dockerdata/qbt          - QBitorrent config and DB
#  /mnt/vol/dockerdata/prowlarr     - Prowlarr config and DB
#  /mnt/vol/dockerdata/overseerr    - Overseerr config and DB
#  /mnt/vol/dockerdata/lib/modules  - Wireguard lib/modules
#  /mnt/vol/dockerdata/wireguard    - Wrieguard config
#
# Folders for Media etc:
#  /mnt/vol/photo                   - Root storage for photo files
#  /mnt/vol/music                   - Root storage for music files
#  /mnt/vol/video                   - Root storage for video files
#  /mnt/vol/video/tv                - folder for Sonarr/Plex TV shows
#  /mnt/vol/video/movies            - folder for Radarr/Plex Movies
#  /mnt/vol/video/downloads         - QBT folder for TV downloads (that Sonarr will process)
#  /mnt/vol/video/downloadsMovies   - QBT folder for Movie downloads (that Radarr will process)
# 
# Note that Sonarr and Radarr don't necessarily need the VPN if you're using Prowlarr for the indexers. 
# But Prowlarr should be behind the VPN to avoid ISPs that block indexers.

#
# Taken from: https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
#


---
services:
  ### ----------------- Plex ----------------- ###
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - /mnt/vol/dockerdata/plex:/config
      - /mnt/vol/video/tv:/tv
      - /mnt/vol/video/movies:/movies
    restart: unless-stopped
  ### ----------------- Sonarr --------------- ###
  sonarr: 
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago  
    volumes:
      - /mnt/vol/dockerdata/sonarr:/config 
      - /mnt/vol/video/tv:/tv #optional
      - /mnt/vol/video/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  ### ----------------- Radarr --------------- ###
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/radarr:/data
      - /mnt/vol/video/movies:/movies #optional
      - /mnt/vol/video/downloadsMovies:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  ### ----------------- Overseer ------------- ###
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  ### ----------------- Wireguard ------------ ###
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy

    environment:
      - PASSWORD_HASH=$$2a$$12$$0Tn96.wvsP4k2AMjjSN9z..HqZpDm9nWGGqtBei5rjIKPXMw7EBS6
      - WG_HOST=172.18.0.1

    volumes:
      - /mnt/vol/dockerdata/wireguard:/etc/wireguard
      - /mnt/vol/dockerdata/lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
      - "8080:8080/tcp"
      - "9696:9696/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
  ### ----------------- Prowlarr ------------ ###
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on: 
      - wg-easy
    network_mode: service:wg-easy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/prowlarr:/config
    # ports:
    #   - 9696:9696
    restart: unless-stopped

  ### ----------------- Jackett ---------- ###
  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest #lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #       - PUID=1000 # Change this to your user ID
  #       - PGID=1000 # Change this to your group ID
  #       - TZ=America/Chicago # Change this to your timezone
  #       - AUTO_UPDATE=true
  #   volumes:
  #       - /opt/pvr/jackett:/config
  #       - /mnt/plex/downloads:/downloads
  #   ports:
  #       - 9117:9117
  #   restart: unless-stopped
  ### ----------------- QBitTorrent ---------- ###
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest 
    container_name: qbittorrent
    depends_on:
    - wg-easy
    network_mode: service:wg-easy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/vol/dockerdata/qbt:/config
      - /mnt/vol/video/Downloads:/downloads #optional