---
services:
  ### ----------------- Sonarr --------------- ###
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/sonarr/data:/data
      - /path/to/tvseries:/data/tv #optional
      - /path/to/downloadclient-downloads:/data/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  ### ----------------- Radarr --------------- ###
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/radarr/data:/data
      - /path/to/movies:/data/movies #optional
      - /path/to/download-client-downloads:/data/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  ### ----------------- Plex ----------------- ###
  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment: host
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /path/to/plex/library:/data
      - /path/to/tvseries:/data/tv
      - /path/to/movies:/data/movies
    # ports:
    #   - 42300:42300
    restart: unless-stopped