---
services:
  ### ----------------- Plex ----------------- ###
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - /path/to/plex/library:/data
      - /path/to/tvseries:/data/tv
      - /path/to/movies:/data/movies
    restart: unless-stopped
  ### ----------------- Sonarr --------------- ###
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago  
    volumes:
      - /path/to/sonarr/data:/data
      - /path/to/tvseries:/data/tv #optional
      - /path/to/downloadclient-downloads:/data/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  ### ----------------- Radarr --------------- ###
  # radarr:
  #   image: lscr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Chicago
  #   volumes:
  #     - /path/to/radarr/data:/data
  #     - /path/to/movies:/data/movies #optional
  #     - /path/to/download-client-downloads:/data/downloads #optional
  #   ports:
  #     - 7878:7878
  #   restart: unless-stopped
  ### ----------------- Overseer ------------- ###
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest x
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /path/to/overseerr/config:/data/config
    ports:
      - 5055:5055
    restart: unless-stopped

    # ### ----------------- Jackett ---------- ###
  jackett:
    image: lscr.io/linuxserver/jackett:latest #lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
        - PUID=1000 # Change this to your user ID
        - PGID=1000 # Change this to your group ID
        - TZ=America/Chicago # Change this to your timezone
        - AUTO_UPDATE=true
    volumes:
        - /opt/pvr/jackett:/data/jackettconfig
        - /mnt/plex/downloads:/data/downloads
    ports:
        - 9117:9117
    restart: unless-stopped

  ### ----------------- Wireguard ------------ ###
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy

    environment:
      - PASSWORD_HASH=$$2a$$12$$0Tn96.wvsP4k2AMjjSN9z..HqZpDm9nWGGqtBei5rjIKPXMw7EBS6
      - WG_HOST=172.18.0.1

    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
      - "8080:8080/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
  ### ----------------- QBitTorrent ---------- ###
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest 
    container_name: qbittorrent
    depends_on:
    - wg-easy
    # network_mode: services:protonwire
    network_mode: service:wg-easy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      # - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /path/to/qbittorrent/appdata:/data/qbitConfig
      - /path/to/downloads:/data/downloads #optional