# Docker compose to set up containers for all services you need:
# VPN
#   QBitTorrent
# Non-VPN
#   Plex, Jellyfin, *arr, Overseerr
#
# Before running docker-compose, you should pre-create all of the following folders.
# create_dirs.sh is a helper script that helps with this
#
# Folders for Docker State:
#  /mnt/vol/dockerdata              - root where this docker-compose.yml should live
#  /mnt/vol/dockerdata/plex         - Plex config and DB
#  /mnt/vol/dockerdata/sonarr       - Sonarr config and DB
#  /mnt/vol/dockerdata/radarr       - Radarr config and DB
#  /mnt/vol/dockerdata/qbt          - QBitorrent config and DB
#  /mnt/vol/dockerdata/prowlarr     - Prowlarr config and DB
#  /mnt/vol/dockerdata/overseerr    - Overseerr config and DB
#  /mnt/vol/dockerdata/jelly        - Jellyfin root folder
#  /mnt/vol/dockerdata/jelly/config - Jellyfin config folder
#  /mnt/vol/dockerdata/jelly/cache  - Jellyfin cache folder
# 
# Folders for Media etc:
#  /mnt/vol/photo                   - Root storage for photo files
#  /mnt/vol/music                   - Root storage for music files
#  /mnt/vol/video                   - Root storage for video files
#  /mnt/vol/video/tv                - folder for Sonarr/Plex TV shows
#  /mnt/vol/video/movies            - folder for Radarr/Plex Movies
#  /mnt/vol/video/Downloads         - QBT folder for downloads \
#
# Note that Sonarr and Radarr don't necessarily need the VPN if you're using Prowlarr for the indexers. 
# But Prowlarr should be behind the VPN to avoid ISPs that block indexers.

# Other Resources
# https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d
# https://linuxiac.com/how-to-set-up-wireguard-vpn-with-docker/
# https://github.com/ivan-pinatti/docker-torrent-box-with-vpn
# https://github.com/RogueOneEcho/how-to-setup-deluge-with-protonvpn-portforward/tree/part-1 

---

services:
  ### ----------------- Plex ----------------- ###
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
    volumes:
      - /mnt/vol/dockerdata/plex:/config
      - /mnt/vol/video/tv:/tv
      - /mnt/vol/video/movies:/movies
    restart: unless-stopped
    
  ### ----------------- JellyFin ----------------- ###
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /mnt/vol/dockerdata/jelly/config:/config
      - /mnt/vol/dockerdata/jelly/cache:/cache
      - type: bind
        source: /mnt/vol/video/tv
        target: /tv
      - type: bind
        source: /mnt/vol/video/movies
        target: /movies
        read_only: true
    restart: 'unless-stopped'
  ### ----------------- Sonarr --------------- ###
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/sonarr:/config
      - /mnt/vol/video/tv:/tv #optional
      - /mnt/vol/video/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.11

  ### ----------------- Radarr --------------- ###
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/radarr:/data
      - /mnt/vol/video/movies:/movies
      - /mnt/vol/video/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.12

  ### ----------------- Overseer ------------- ###
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.13

  ### ----------------- Prowlarr ------------ ###
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/vol/dockerdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.14

  ### ----------------- Gluetun -- Proton VPN ---------- ### 
  gluetun:
    image: qmcgaw/gluetun
    container_name: glue
    init: true
    env_file: "env/proton.env"
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: "cMWMVBSEJ3nm4DWz5mc+bWRKoJN6Ab63ZfZQmjdsH2c="
      SERVER_COUNTRIES: "United States"
      SERVER_CITIES: "Chicago"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 5000:5000
      # Qbit ports
      - 8080:8080
      - 16881:16881
      # Deluge Ports
      - 8112:8112
      - 17881:17881
      - 17881:17881/udp
      - 58846:58846 
    restart: unless-stopped
    networks:
      container_net:
        ipv4_address: 172.28.1.20

  ### ----------------- QBitTorrent ---------- ### 
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbit
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - TORRENTING_PORT=16881
    volumes:
      - /mnt/vol/dockerdata/qbt:/config
      - /mnt/vol/video/Downloads:/downloads

  ### ----------------- Deluge ---------- ### 
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DELUGE_LOGLEVEL=info
    volumes:
      - /mnt/vol/dockerdata/deluge:/config
      - /mnt/vol/video/Downloads:/downloads
    restart: unless-stopped

networks:
  container_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
          gateway: 172.28.1.1