###
# This is some of the other stuff that I was thinking about using / tried using for the vpn / torrent nodes
###

# ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp

  ### ----------------- VPN OF SOME KIND ------------ ###
  # qbittorrent-wireguard:
  #   # secrets:
  #   #   - "webui_pass"
  #   cap_add:
  #     - "NET_ADMIN"
  #   container_name: "qbittorrent-wireguard"
  #   entrypoint:
  #     - "/bin/bash"
  #     - "/start.sh"
  #   environment:
  #     - "PUID=1234"
  #     - "PGID=567"
  #     - "LAN_NETWORK=192.168.1.0/24"
  #     - "QBT_LEGAL_NOTICE=confirm"
  #   image: "docker.io/tenseiken/qbittorrent-wireguard:latest"
  #   ipc: "private"
  #   network_mode: "bridge"
  #   ports:
  #     - "8999:8999/tcp"
  #     - "8999:8999/udp"
  #     - "8080:8080/tcp"
  #   restart: "unless-stopped"
  #   security_opt:
  #     - "label=disable"
  #   stdin_open: true
  #   sysctls:
  #     - "net.ipv4.conf.all.rp_filter=2"
  #     - "net.ipv4.conf.all.src_valid_mark=1"
  #     - "net.ipv6.conf.all.disable_ipv6=1"
  #   tty: true
  #   volumes:
  #     - "/host/path/to/downloads:/data/downloads"
  #     - "/host/path/to/config:/data/config"
  #   working_dir: "/opt"

# secrets:
#   webui_pass:
#     file: "/path/to/webui_pass"


  ### --------------------- ###
  ### ----- Proton VPN ---- ###
  ### --------------------- ###
  # protonwire:
  #   container_name: protonwire
  #   # Use semver tags or sha256 hashes of manifests.
  #   # using latest tag can lead to issues when used with
  #   # automatic image updaters like watchtower/podman.
  #   image: ghcr.io/tprasadtp/protonwire:latest
  #   init: true
  #   restart: unless-stopped
  #   environment:
  #     # Quote this value as server name can contain '#'.
  #     PROTONVPN_SERVER: "node-nl-96.protonvpn.net"  # NL-FREE#100070
  #     # Set this to 1 to show debug logs for issue forms.
  #     DEBUG: "0"
  #     # Set this to 0 to disable kill-switch.
  #     KILL_SWITCH: "1"
  #   # NET_ADMIN capability is mandatory!
  #   cap_add:
  #     - NET_ADMIN
  #   # sysctl net.ipv4.conf.all.rp_filter is mandatory!
  #   # net.ipv6.conf.all.disable_ipv6 disables IPv6 as protonVPN does not support IPv6.
  #   # 'net.*' sysctls are not required on application containers,
  #   # as they share network stack with protonwire container.
  #   sysctls:
  #     net.ipv4.conf.all.rp_filter: 2
  #     net.ipv6.conf.all.disable_ipv6: 1
  #   volumes:
  #     - type: tmpfs
  #       target: /tmp
  #     - type: bind
  #       source: private.key
  #       target: /etc/protonwire/private-key
  #       read_only: true
  #   ports:
  #     - 8000:80
  ### --------------------- ###
  ### --- WireGuard VPN --- ###
  ### --------------------- ###
  # wireguard:
  #   image: lscr.io/linuxserver/wireguard:latest
  #   container_name: wireguard
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE #optional
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Chicago
  #     # - SERVERURL=wireguard.domain.com #optional
  #     - SERVERPORT=51820 #optional
  #     - PEERS=1 #optional
  #     - PEERDNS=auto #optional
  #     - INTERNAL_SUBNET=10.13.13.0 #optional
  #     - ALLOWEDIPS=0.0.0.0/0 #optional
  #     # - PERSISTENTKEEPALIVE_PEERS= #optional
  #     - LOG_CONFS=true #optional
  #   volumes:
  #     - /path/to/wireguard/config:/data/config
  #     # - /lib/modules:/lib/modules #optional
  #   ports:
  #     - 8080:8080
  #     - 51820:51820/udp
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   restart: unless-stopped
