services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: glue
    init: true
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: "cMWMVBSEJ3nm4DWz5mc+bWRKoJN6Ab63ZfZQmjdsH2c="
      SERVER_COUNTRIES: "United States"
      SERVER_CITIES: "Chicago"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports: # ports you want to forward over VPN
      - 5000:5000
      - 6881:6881
      - 8080:8080
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: torr_test
    network_mode: service:gluetun #protonwire
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/vol/dockerdata/qbt:/config
      - /mnt/vol/video/Downloads:/downloads # optional

  # protonwire:
  #   container_name: protonwire
  #   # Use semver tags or sha256 hashes of manifests.
  #   # using latest tag can lead to issues when used with
  #   # automatic image updaters like watchtower/podman.
  #   image: ghcr.io/tprasadtp/protonwire:latest
  #   init: true
  #   restart: unless-stopped
  #   environment:
  #     # Quote this value as server name can contain '#'.
  #     PROTONVPN_SERVER: "149.40.58.146" #"node-us-64.protonvpn.net"  # NL-FREE#100070
  #     # WIREGUARD_PRIVATE_KEY: "gLGL0//1k4LNjX4deP6bCQdUiBZZJTUCjy8EyBXs0Eo="
  #     # Set this to 1 to show debug logs for issue forms.
  #     DEBUG: "0"
  #     # Set this to 0 to disable kill-switch.
  #     KILL_SWITCH: "1"
  #   # NET_ADMIN capability is mandatory!
  #   cap_add:
  #     - NET_ADMIN
  #   # sysctl net.ipv4.conf.all.rp_filter is mandatory!
  #   # net.ipv6.conf.all.disable_ipv6 disables IPv6 as protonVPN does not support IPv6.
  #   # 'net.*' sysctls are not required on application containers,
  #   # as they share network stack with protonwire container.
  #   sysctls:
  #     net.ipv4.conf.all.rp_filter: 2
  #     net.ipv6.conf.all.disable_ipv6: 1
  #   volumes:
  #     # - type: tmpfs
  #     #   target: /tmp
  #     - /mnt/vol/dockerdata/protonwire:/etc/protonwire
  #     - type: bind
  #       source: priv
  #       target: /etc/protonwire/private-key
  #       read_only: true
  #   ports:
  #     - 8080:8080
  # This is sample application which will be routed over VPN
  # Replace this with your preferred application(s).
  # caddy_proxy:
  #   image: caddy:latest
  #   network_mode: service:protonwire
  #   command: |
  #     caddy reverse-proxy \
  #         --change-host-header \
  #         --from :80 \
  #         --to https://ip.me:443
    # ports:
    #   - 8080:8080
    # networks:
    #   container_net:
    #     ipv4_address: 172.28.0.21

    # protonwire:
  #   container_name: protonwire
  #   image: ghcr.io/tprasadtp/protonwire:latest
  #   init: true
  #   restart: unless-stopped
  #   environment:
  #     # PROTONVPN_SERVER: "87.249.134.139" #IL 164 "79.127.136.222" # <-- IL-596 CO-TOR -- "84.17.63.17" # US-FREE "149.40.58.146" \
  #     PROTONVPN_SERVER: "79.127.220.249"
  #     DEBUG: "0"
  #     # Set this to 0 to disable kill-switch
  #     KILL_SWITCH: "0"
  #     # IPCHECK_INTERVAL: "0"
  #     WIREGUARD_PRIVATE_KEY: "cMWMVBSEJ3nm4DWz5mc+bWRKoJN6Ab63ZfZQmjdsH2c=" # "gJVRGKYmBn/P4Yi6gPagSOVa0IvdeIT3ASG9q3UhG0c="
  #   cap_add:
  #     - NET_ADMIN
  #   sysctls:
  #     net.ipv4.conf.all.rp_filter: 2
  #     net.ipv6.conf.all.disable_ipv6: 1
  #   volumes:
  #     - /mnt/vol/dockerdata/protonwire:/etc/protonwire
  #   ports:
  #     # Qbit ports
  #     - 8080:8080
  #     - 16881:16881
  #     # Deluge Ports
  #     - 8112:8112
  #     - 17881:17881
  #     - 17881:17881/udp
  #     - 58846:58846 
  #   networks:
  #     container_net:
  #       ipv4_address: 172.28.1.20