---

services:
  ### ----------------- Deluge VPN ------------- ###
  deluge-vpn:
    container_name: deluge-vpn
    image: binhex/arch-delugevpn
    ports:
      - 8112:8112
      - 8118:8118
      - 9118:9118 
      - 58846:58846 
      - 58946:58946 
      - 58946:58946/udp 
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/vol/video/downloads:/data
      - /mnt/vol/dockerdata/deluge/config
    environment:
      VPN_ENABLED: yes
      VPN_USER: "tgrin" 
      VPN_PASS: "7324102"
      VPN_PROV: pia
      VPN_CLIENT: openvpn
      ENABLE_STARTUP_SCRIPTS: yes
      ENABLE_PRIVOXY: yes
      STRICT_PORT_FORWARD: no
      USERSPACE_WIREGUARD: no
      ENABLE_SOCKS: yes
      SOCKS_USER: "tgrin"
      SOCKS_PASS: "7324102"
      LAN_NETWORK: 192.168.0.0/24
      # NAME_SERVERS: <name server ip(s)> \
      DELUGE_DAEMON_LOG_LEVEL: info
      DELUGE_WEB_LOG_LEVEL: info
      DELUGE_ENABLE_WEBUI_PASSWORD: yes
      VPN_INPUT_PORTS: 1234
      VPN_OUTPUT_PORTS: 5678
      DEBUG: true
      UMASK: 000
      PUID: 1000
      PGID: 1000